/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

package org.mozilla.zest.core.v1;

import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;


// TODO: Auto-generated Javadoc
/**
 * The Class ZestScript.
 */
public class ZestScript extends ZestStatement implements ZestContainer {

	/** The Constant VERSION. */
	public static final String VERSION = "0.2";

	/** The Constant ZEST_URL. */
	public static final String ZEST_URL = "https://developer.mozilla.org/en-US/docs/Zest";
	
	/** The Constant ABOUT. */
	public static final String ABOUT = "This is a Zest script. For more details about Zest visit " + ZEST_URL;

	/**
	 * The Enum Type.
	 */
	public enum Type {/** The Targeted. */
Targeted, /** The Active. */
 Active, /** The Passive. */
 Passive };

	/** The about. */
	private String about = ABOUT;
	
	/** The zest version. */
	private String zestVersion = VERSION;
	
	/** The generated by. */
	private String generatedBy;
	
	/** The author. */
	private String author;
	
	/** The title. */
	private String title;
	
	/** The description. */
	private String description;
	
	/** The prefix. */
	private String prefix;
	
	/** The type. */
	private String type;
	
	/** The tokens. */
	private ZestVariables tokens = new ZestVariables();
	
	/** The statements. */
	private List<ZestStatement> statements = new ArrayList<ZestStatement>();
	
	/** The authentication. */
	private List<ZestAuthentication> authentication = new ArrayList<ZestAuthentication>();
	
	/** The common tests. */
	private List<ZestStatement> commonTests = new ArrayList<ZestStatement>();
	
	/**
	 * Instantiates a new zest script.
	 */
	public ZestScript () {
		super();
	}
	
	/**
	 * Instantiates a new zest script.
	 *
	 * @param title the title
	 * @param description the description
	 * @param type the type
	 */
	public ZestScript (String title, String description, String type) {
		this();
		this.title = title;
		this.description = description;
		this.setType(type);
	}
	
	/**
	 * Instantiates a new zest script.
	 *
	 * @param title the title
	 * @param description the description
	 * @param type the type
	 */
	public ZestScript (String title, String description, Type type) {
		this();
		this.title = title;
		this.description = description;
		this.setType(type);
	}
	
	/**
	 * Sets the type.
	 *
	 * @param type the new type
	 */
	public void setType(Type type) {
		this.type = type.name();
	}
	
	/**
	 * Sets the type.
	 *
	 * @param type the new type
	 */
	public void setType(String type) {
		try {
			Type.valueOf(type);
		} catch (Exception e) {
			throw new IllegalArgumentException("Unsupported type: " + type);
		}
		this.type = type;
	}

	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	public String getType() {
		return type;
	}

	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestStatement#deepCopy()
	 */
	@Override
	public ZestScript deepCopy() {
		ZestScript script = new ZestScript();
		this.duplicateTo(script);
		return script;
	}
	
	/**
	 * Duplicate to.
	 *
	 * @param script the script
	 */
	public void duplicateTo(ZestScript script) {
		script.about = this.about;
		script.zestVersion = this.zestVersion;
		script.generatedBy = this.generatedBy;
		script.author = this.author;
		script.title = this.title;
		script.description = this.description;
		script.prefix = this.prefix;
		script.tokens = this.tokens.deepCopy();
		script.type = this.type;
		
		for (ZestStatement zr : this.getStatements()) {
			script.add(zr.deepCopy());
		}
		for (ZestAuthentication za : this.getAuthentication()) {
			script.addAuthentication((ZestAuthentication)za.deepCopy());
		}
		for (ZestStatement zr : this.getCommonTests()) {
			script.addCommonTest(zr.deepCopy());
		}
		script.setTokens(this.getTokens().deepCopy());
	}

	/**
	 * Adds the.
	 *
	 * @param req the req
	 */
	public void add(ZestStatement req) {
		this.add(this.statements.size(), req);
	}
	
	/**
	 * Adds the.
	 *
	 * @param index the index
	 * @param req the req
	 */
	public void add(int index, ZestStatement req) {
		ZestStatement prev = this;
		if (index == this.statements.size()) {
			// Add at the end
			this.statements.add(req);
			
		} else {
			this.statements.add(index, req);
		}
		if (index > 0) {
			prev = this.statements.get(index-1);
		}
		// This will wire everything up
		req.insertAfter(prev);
		updateTokens(req);
	}
	
	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestContainer#move(int, org.mozilla.zest.core.v1.ZestStatement)
	 */
	public void move(int index, ZestStatement req) {
		this.remove(req);
		this.add(index, req);
	}
	
	/**
	 * Removes the.
	 *
	 * @param req the req
	 */
	public void remove(ZestStatement req) {
		this.statements.remove(req);
		req.remove();
	}
	
	/**
	 * Removes the statement.
	 *
	 * @param index the index
	 */
	public void removeStatement(int index) {
		this.remove(this.statements.get(index));
	}
	
	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestContainer#getStatement(int)
	 */
	public ZestStatement getStatement (int index) {
		for (ZestStatement zr : this.getStatements()) {
			if (zr.getIndex() == index) {
				return zr;
			}
			if (zr instanceof ZestContainer) {
				ZestStatement stmt = ((ZestContainer)zr).getStatement(index);
				if (stmt != null) {
					return stmt;
				}
			}
		}

		return null;
	}
	
	/**
	 * Adds the common test.
	 *
	 * @param req the req
	 */
	public void addCommonTest(ZestStatement req) {
		this.addCommonTest(this.commonTests.size(), req);
	}
	
	/**
	 * Adds the common test.
	 *
	 * @param index the index
	 * @param req the req
	 */
	public void addCommonTest(int index, ZestStatement req) {
		ZestStatement prev = this;
		if (index == this.commonTests.size()) {
			// Add at the end
			this.commonTests.add(req);
			
		} else {
			this.commonTests.add(index, req);
		}
		if (index > 0) {
			prev = this.commonTests.get(index-1);
		}
		// This will wire everything up
		req.insertAfter(prev);
	}
	
	/**
	 * Move common test.
	 *
	 * @param index the index
	 * @param req the req
	 */
	public void moveCommonTest(int index, ZestStatement req) {
		this.removeCommonTest(req);
		this.addCommonTest(index, req);
	}
	
	/**
	 * Removes the common test.
	 *
	 * @param req the req
	 */
	public void removeCommonTest(ZestStatement req) {
		this.commonTests.remove(req);
		req.remove();
	}
	
	/**
	 * Removes the common test.
	 *
	 * @param index the index
	 */
	public void removeCommonTest(int index) {
		this.remove(this.commonTests.get(index));
	}
	
	/**
	 * Gets the common test.
	 *
	 * @param index the index
	 * @return the common test
	 */
	public ZestStatement getCommonTest (int index) {
		for (ZestStatement zr : this.getCommonTests()) {
			if (zr.getIndex() == index) {
				return zr;
			}
			if (zr instanceof ZestContainer) {
				ZestStatement stmt = ((ZestContainer)zr).getStatement(index);
				if (stmt != null) {
					return stmt;
				}
			}
		}

		return null;
	}
	
	/**
	 * Gets the title.
	 *
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the title.
	 *
	 * @param title the new title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the statements.
	 *
	 * @return the statements
	 */
	public List<ZestStatement> getStatements() {
		return statements;
	}

	/**
	 * Sets the statements.
	 *
	 * @param statements the new statements
	 */
	public void setStatements(List<ZestStatement> statements) {
		this.statements = statements;
	}
	
	/**
	 * Adds the authentication.
	 *
	 * @param auth the auth
	 */
	public void addAuthentication(ZestAuthentication auth) {
		this.authentication.add(auth);
	}

	/**
	 * Removes the authentication.
	 *
	 * @param auth the auth
	 */
	public void removeAuthentication(ZestAuthentication auth) {
		this.authentication.remove(auth);
	}

	/**
	 * Gets the authentication.
	 *
	 * @return the authentication
	 */
	public List<ZestAuthentication> getAuthentication() {
		return authentication;
	}

	/**
	 * Sets the authentication.
	 *
	 * @param authentication the new authentication
	 */
	public void setAuthentication(List<ZestAuthentication> authentication) {
		this.authentication = authentication;
	}
	
	/**
	 * Gets the common tests.
	 *
	 * @return the common tests
	 */
	public List<ZestStatement> getCommonTests() {
		return commonTests;
	}

	/**
	 * Sets the common tests.
	 *
	 * @param statements the new common tests
	 */
	public void setCommonTests(List<ZestStatement> statements) {
		this.commonTests = statements;
	}
	
	/**
	 * Gets the prefix.
	 *
	 * @return the prefix
	 */
	public String getPrefix() {
		return prefix;
	}

	/**
	 * Sets the prefix.
	 *
	 * @param newPrefix the new prefix
	 * @throws MalformedURLException the malformed url exception
	 */
	public void setPrefix(String newPrefix) throws MalformedURLException {
		this.setPrefix(this.prefix, newPrefix);
	}

	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestStatement#setPrefix(java.lang.String, java.lang.String)
	 */
	public void setPrefix(String oldPrefix, String newPrefix) throws MalformedURLException {
		if (newPrefix != null && newPrefix.length() > 0) {
			for (ZestStatement stmt : this.statements) {
				stmt.setPrefix(oldPrefix, newPrefix);
			}
		}
		this.prefix = newPrefix;
	}

	/**
	 * Gets the tokens.
	 *
	 * @return the tokens
	 */
	public ZestVariables getTokens() {
		return this.tokens;
	}

	/**
	 * Sets the tokens.
	 *
	 * @param tokens the new tokens
	 */
	public void setTokens(ZestVariables tokens) {
		this.tokens = tokens;
	}

	/**
	 * Update tokens.
	 *
	 * @param statement the statement
	 */
	private void updateTokens(ZestStatement statement) {
		Set<String> allTokens = statement.getTokens(this.tokens.getTokenStart(), this.tokens.getTokenEnd());
		for (String str : allTokens) {
			// Will default if not present
			this.tokens.addToken(str);
		}
	}

	/**
	 * Gets the zest version.
	 *
	 * @return the zest version
	 */
	public String getZestVersion() {
		return zestVersion;
	}

	/**
	 * Sets the zest version.
	 *
	 * @param zestVersion the new zest version
	 */
	public void setZestVersion(String zestVersion) {
		if (! VERSION.equals(zestVersion)) {
			throw new IllegalArgumentException("Version " + zestVersion + " not supported by this class");
		}
		this.zestVersion = zestVersion;
	}

	/**
	 * Gets the generated by.
	 *
	 * @return the generated by
	 */
	public String getGeneratedBy() {
		return generatedBy;
	}

	/**
	 * Sets the generated by.
	 *
	 * @param generatedBy the new generated by
	 */
	public void setGeneratedBy(String generatedBy) {
		this.generatedBy = generatedBy;
	}

	/**
	 * Gets the about.
	 *
	 * @return the about
	 */
	public String getAbout() {
		return about;
	}

	/**
	 * Sets the about.
	 *
	 * @param about the new about
	 */
	public void setAbout(String about) {
		this.about = about;
	}

	/**
	 * Gets the author.
	 *
	 * @return the author
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * Sets the author.
	 *
	 * @param author the new author
	 */
	public void setAuthor(String author) {
		this.author = author;
	}

	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestStatement#getTokens(java.lang.String, java.lang.String)
	 */
	@Override
	public Set<String> getTokens(String tokenStart, String tokenEnd) {
		Set<String> tokens = new HashSet<String>();
		for (ZestStatement stmt : this.statements) {
			tokens.addAll(stmt.getTokens(tokenStart, tokenEnd));
		}
		return tokens;
	}

	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestContainer#getIndex(org.mozilla.zest.core.v1.ZestStatement)
	 */
	@Override
	public int getIndex (ZestStatement child) {
		return this.statements.indexOf(child);
	}

	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestContainer#getLast()
	 */
	@Override
	public ZestStatement getLast() {
		return null;
	}

	/* (non-Javadoc)
	 * @see org.mozilla.zest.core.v1.ZestContainer#getChildBefore(org.mozilla.zest.core.v1.ZestStatement)
	 */
	@Override
	public ZestStatement getChildBefore(ZestStatement child) {
		if (this.statements.contains(child)) {
			int childIndex = this.statements.indexOf(child);
			if (childIndex > 1) {
				return this.statements.get(childIndex-1);
			}
		}
		return null;
	}
	
}
